### ISSUE TITLE
Checkout Tasty

### ISSUE THREAD

**Issue by biohazard999** [Tyrrrz/Hallstatt#1]
Hi @Tyrrrz not an issue, just wanted to know about [Tasty](https://tasty.xenial.io/). Seams like we had the same idea at the same time :) Good Work!

**Comment by Tyrrrz** [comment]
Hey @biohazard999, thanks for sharing your project.
They do appear similar! I was more focused on the top-level statements aspect and hit a wall due to the fact that only one such code file per project is allowed. I really wanted to avoid having to write classes and methods. 😅

**Comment by biohazard999** [comment]
Hi @Tyrrrz was my first idea too, but let's see what the next C# features we can expect!
It also can be [benifitial](https://github.com/xenial-io/Xenial.Identity/blob/main/src/Xenial.Identity.Xpo.Storage.Tests/IntegrationTests/ResourceStoreTests.cs)

But great job ob the `TestAdapter`. Thats something I avoided, cause I'm not familar with the API's. But looking at your source, I probably should give it a shot!
